[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "psifx"
version = "0.0.0"
description = "Psychological and Social Interactions Feature Extraction"
readme = "README.md"
requires-python = ">=3.7"
authors = [
    {name="Guillaume Rochette", email="rochette.guillaume@gmail.com"},
    {name="Matthew Vowels", email="matthew.vowels@unil.ch"},
]
keywords = ["TODO"]
classifiers = [
    "Development Status :: 1 - Planning",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dynamic = ["dependencies"]

[project.urls]
homepage = "https://github.com/GuillaumeRochette/psifx"
documentation = "https://github.com/GuillaumeRochette/psifx"
repository = "https://github.com/GuillaumeRochette/psifx"

[project.scripts]
psifx-stream-separation = "psifx.stream.separation_tool:cli_main"
psifx-video-pose-mediapipe = "psifx.video.pose.mediapipe.inference_tool:cli_main"
psifx-audio-diarization-pyannote = "psifx.audio.diarization.pyannote.inference_tool:cli_main"
psifx-audio-transcription-whisper = "psifx.audio.transcription.whisper.inference_tool:cli_main"


#[tool.setuptools.packages]
#find = {}

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
